import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br" className="antialiased">
      <body className={inter.className}>
        <main className="m-auto mt-20 px-4 pb-4 md:max-w-4xl lg:max-w-6xl">
          {children}
        </main>
      </body>
    </html>
  );
}
